### ISSUE TITLE
documentation: redraw database model

### ISSUE THREAD

**Issue by rsteph-de** [ubrostock/purl_server#29]
Das Datenmodell muss neu gezeichnet werden
Dazu verwenden wir https://www.diagrams.net/ 
Export als SVG mit eingebettetem QellCode.

Bitte nochmal die Spalten prüfen: In der Historie-Tabelle fehlt z.B. `user_id`

**Comment by skasten-de** [comment]
SVG Datei in Wiki aktualisiert
