### ISSUE TITLE
api: documentation with Open API 3.0

### ISSUE THREAD

**Issue by rsteph-de** [ubrostock/purl_server#35]
provide the necessary API documentation for the REST-Endpoints
getting started: https://www.baeldung.com/spring-rest-openapi-documentation

URL zur HTML-Seite der API-Documentation: http://localhost:8080/api/swagger-ui

Der Endpoint /api/domain ist vollständig annotiert

**TODO** alle /api  und /info Endpoints enstprechend mit Annotationen beschreiben.

**Comment by eo33** [comment]
Hi are you still looking for documentation help? I would like to contribute to this project.

**Comment by ghost** [comment]
Hello. Do you still need documentation help?

**Comment by rsteph-de** [comment]
Thank you for your help offerings. We are nearly done with the API documentation. We wanted to do it ourselves to learn how to use and parameterize OpenAPI / Swagger.

**Comment by ghost** [comment]
Well done.
