### ISSUE TITLE
Purl: Disable delete-button after successful delete

### ISSUE THREAD

**Issue by skasten-de** [ubrostock/purl_server#43]

**Comment by rsteph-de** [comment]
Bitte auch nochmal das HTML für alle Ergebnisseiten (beim Erstellen, Bearbeiten, Löschen) prüfen
Die Success-Meldung sollte als Bootstrap Alert umgesetzt werden:
`<div class="alert alert-success">PURL bearbeitet!</div>`

Beim PURL Löschen ist es im Moment nur ein 'farbiger' Text:
`<span class="text-success">PURL gelöscht!</span>`

**Comment by rsteph-de** [comment]
use `th:disabled` instead of `th:attr`
https://www.thymeleaf.org/doc/tutorials/3.0/usingthymeleaf.html#fixed-value-boolean-attributes
